package main

import "strings"

var legacyRawSaveProfiles = map[string]strictRawSaveValidationProfile{
	"pc-engine": {
		SystemSlug:  "pc-engine",
		DisplayName: "pc engine / turbografx-16",
		ParserID:    "pc-engine-raw-bram",
		AllowedExts: map[string]struct{}{
			"brm": {},
			"bkr": {},
			"ram": {},
			"sav": {},
			"srm": {},
		},
		AllowedSizes: map[int]struct{}{
			2000:   {}, // PC Engine BRAM user bytes are often exposed without chip padding.
			2048:   {},
			8192:   {},
			32768:  {},
			131072: {}, // Memory Base 128 style backup RAM.
		},
		RequireROMSHA1:       true,
		RequireDeclared:      true,
		RequireHelperOrStore: true,
		RejectBlank:          true,
		SparseWarningCutoff:  16,
		Warning:              "PC Engine support is raw backup RAM validation; no per-game structural decoder is available yet",
	},
	"atari-lynx": {
		SystemSlug:  "atari-lynx",
		DisplayName: "atari lynx",
		ParserID:    "atari-lynx-raw-eeprom",
		AllowedExts: map[string]struct{}{
			"eep":    {},
			"eeprom": {},
			"ram":    {},
			"sav":    {},
			"srm":    {},
		},
		AllowedSizes: map[int]struct{}{
			128:  {},
			256:  {},
			512:  {},
			1024: {},
			2048: {},
			8192: {},
		},
		RequireROMSHA1:       true,
		RequireDeclared:      true,
		RequireHelperOrStore: true,
		RejectBlank:          true,
		SparseWarningCutoff:  8,
		Warning:              "Atari Lynx support is raw EEPROM validation; most commercial Lynx games do not carry persistent EEPROM data",
	},
	"wonderswan": {
		SystemSlug:  "wonderswan",
		DisplayName: "wonderswan",
		ParserID:    "wonderswan-raw-backup",
		AllowedExts: map[string]struct{}{
			"eep":    {},
			"eeprom": {},
			"ram":    {},
			"sav":    {},
			"srm":    {},
		},
		AllowedSizes: map[int]struct{}{
			128:    {},
			256:    {},
			512:    {},
			1024:   {},
			2048:   {},
			8192:   {},
			32768:  {},
			65536:  {},
			131072: {},
		},
		RequireROMSHA1:       true,
		RequireDeclared:      true,
		RequireHelperOrStore: true,
		RejectBlank:          true,
		SparseWarningCutoff:  8,
		Warning:              "WonderSwan support is raw cartridge backup validation; no per-game structural decoder is available yet",
	},
	"sg-1000": {
		SystemSlug:  "sg-1000",
		DisplayName: "sg-1000",
		ParserID:    "sg-1000-raw-backup",
		AllowedExts: map[string]struct{}{
			"ram": {},
			"sav": {},
			"srm": {},
		},
		AllowedSizes: map[int]struct{}{
			128:   {},
			256:   {},
			512:   {},
			1024:  {},
			2048:  {},
			4096:  {},
			8192:  {},
			16384: {},
			32768: {},
		},
		RequireROMSHA1:       true,
		RequireDeclared:      true,
		RequireHelperOrStore: true,
		RejectBlank:          true,
		SparseWarningCutoff:  8,
		Warning:              "SG-1000 support is conservative raw save validation for cartridges or runtimes that expose persistent save RAM",
	},
	"colecovision": {
		SystemSlug:  "colecovision",
		DisplayName: "colecovision",
		ParserID:    "colecovision-raw-backup",
		AllowedExts: map[string]struct{}{
			"eep":    {},
			"eeprom": {},
			"nv":     {},
			"nvram":  {},
			"ram":    {},
			"sav":    {},
			"srm":    {},
		},
		AllowedSizes: map[int]struct{}{
			128:   {},
			256:   {},
			512:   {},
			1024:  {},
			2048:  {},
			4096:  {},
			8192:  {},
			16384: {},
			32768: {},
		},
		RequireROMSHA1:       true,
		RequireDeclared:      true,
		RequireHelperOrStore: true,
		RejectBlank:          true,
		SparseWarningCutoff:  8,
		Warning:              "ColecoVision support is conservative raw NVRAM/EEPROM validation for runtimes that expose persistent save data",
	},
	"atari-jaguar": {
		SystemSlug:  "atari-jaguar",
		DisplayName: "atari jaguar",
		ParserID:    "atari-jaguar-raw-eeprom",
		AllowedExts: map[string]struct{}{
			"eep":    {},
			"eeprom": {},
			"nv":     {},
			"nvram":  {},
			"ram":    {},
			"sav":    {},
			"srm":    {},
		},
		AllowedSizes: map[int]struct{}{
			128:    {},
			256:    {},
			512:    {},
			1024:   {},
			2048:   {},
			8192:   {},
			32768:  {},
			131072: {},
		},
		RequireROMSHA1:       true,
		RequireDeclared:      true,
		RequireHelperOrStore: true,
		RejectBlank:          true,
		SparseWarningCutoff:  8,
		Warning:              "Atari Jaguar support is raw EEPROM/NVRAM validation; no per-game structural decoder is available yet",
	},
	"3do": {
		SystemSlug:  "3do",
		DisplayName: "3do",
		ParserID:    "3do-raw-nvram",
		AllowedExts: map[string]struct{}{
			"nv":    {},
			"nvram": {},
			"ram":   {},
			"sav":   {},
			"srm":   {},
		},
		AllowedSizes: map[int]struct{}{
			32768:  {},
			131072: {},
		},
		RequireROMSHA1:       true,
		RequireDeclared:      true,
		RequireHelperOrStore: true,
		RejectBlank:          true,
		SparseWarningCutoff:  16,
		Warning:              "3DO support is raw NVRAM validation; no per-game structural decoder is available yet",
	},
}

func validateLegacyRawSave(input saveCreateInput, detection saveSystemDetectionResult, systemSlug string) consoleValidationResult {
	profile, ok := legacyRawSaveProfiles[strings.ToLower(strings.TrimSpace(systemSlug))]
	if !ok {
		return consoleValidationResult{}
	}
	return validateStrictRawSaveClass(input, detection, profile)
}
